import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFile,readdir} from 'node:fs/promises'
import {createHash} from 'node:crypto'
import {startPostgres,literal} from './helpers/postgres.mjs'
const root=new URL('../docs/15-APLICACION-CONTROLADA/',import.meta.url)
const sql=n=>readFile(new URL(n,root),'utf8')
const version='20261002000000'
const initialize=async()=>{const db=await startPostgres();await db.migrate(n=>n<version);const names=(await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(n=>n.endsWith('.sql')&&n<version).sort();await db.query(`create schema supabase_migrations;create table supabase_migrations.schema_migrations(version text primary key,name text,statements text[]);insert into supabase_migrations.schema_migrations(version,name,statements)values ${names.map(n=>`(${literal(n.slice(0,14))},${literal(n.slice(15,-4))},array[]::text[])`).join(',')};insert into public.weddings(id,slug,couple_name,payment_enabled) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','ricardo-sabrina-2026','Synthetic',true);insert into public.registrations(id,wedding_id,guest_count,adult_count,payment_method,total_amount) values('11111111-1111-4111-8111-111111111111','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',1,1,'cash',35000),('22222222-2222-4222-8222-222222222222','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',1,1,'mercadopago',35000);insert into public.payments(registration_id,provider,amount,external_reference,provider_preference_id)values('22222222-2222-4222-8222-222222222222','mercadopago',35000,'22222222-2222-4222-8222-222222222222','historical-preference');`);return db}
test('Sprint 15 frozen SQL is byte exact, hashes match and package preserves history/security',async()=>{const db=await initialize();try{const manifest=JSON.parse(await sql('SHA256.json'));const source=await readFile(new URL('../'+manifest.source.path,import.meta.url));assert.equal(createHash('sha256').update(source).digest('hex'),manifest.source.sha256);for(const[n,h]of Object.entries(manifest.files))assert.equal(createHash('sha256').update(await readFile(new URL(n,root))).digest('hex'),h,n);const apply=await sql(`10-APPLY-${version}.sql`);assert.equal(apply.split('-- BEGIN EXACT REVIEWED SOURCE\n')[1].split('-- END EXACT REVIEWED SOURCE\n')[0],source.toString('utf8'));await db.query(await sql('00-BASELINE-READ-ONLY.sql'));const before=await db.query("select jsonb_agg(to_jsonb(r) order by id) from public.registrations r");const publicTables=await db.query("select jsonb_agg(relname order by relname) from pg_class where relnamespace='public'::regnamespace and relkind in ('r','p')");
const snapshotCheck=`DO $qa$ BEGIN IF EXISTS(select 1 from pg_class where relname='sprint15_review_snapshot') THEN RAISE EXCEPTION 'Snapshot remains after COMMIT'; END IF; END; $qa$;`;
const during=`DO $qa$ BEGIN IF NOT EXISTS(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.oid='pg_temp.sprint15_review_snapshot'::regclass and c.relpersistence='t' and n.nspname like 'pg_temp_%') THEN RAISE EXCEPTION 'Snapshot not temporary'; END IF; IF to_regclass('public.sprint15_review_snapshot') IS NOT NULL THEN RAISE EXCEPTION 'Public snapshot created'; END IF; IF has_table_privilege('anon','pg_temp.sprint15_review_snapshot','SELECT') OR has_table_privilege('authenticated','pg_temp.sprint15_review_snapshot','SELECT') OR has_table_privilege('service_role','pg_temp.sprint15_review_snapshot','SELECT') THEN RAISE EXCEPTION 'Snapshot readable by runtime role'; END IF; END; $qa$;`;
await db.query(apply.replace('DROP TABLE pg_temp.sprint15_review_snapshot;',during+' DROP TABLE pg_temp.sprint15_review_snapshot;')+snapshotCheck);
assert.equal(await db.query("select jsonb_agg(relname order by relname) from pg_class where relnamespace='public'::regnamespace and relkind in ('r','p')"),publicTables);assert.equal(await db.query("select jsonb_agg(to_jsonb(r)-'payment_reported_at' order by id) from public.registrations r"),before);assert.equal(await db.query(`select md5(statements[1]) from supabase_migrations.schema_migrations where version='${version}'`),createHash('md5').update(source.toString('utf8').replace(/\r\n/g,'\n')).digest('hex'));for(const name of ['11-POSTFLIGHT-READ-ONLY.sql','20-INTEGRITY-READ-ONLY.sql'])await db.query(await sql(name));for(const signature of ['prepare_transfer_payment(uuid,text)','report_transfer_payment(uuid,text)','approve_transfer_payment(uuid)'])assert.equal(await db.query(`select pg_get_userbyid(proowner) from pg_proc where oid='public.${signature}'::regprocedure`),'postgres');await assert.rejects(db.query(apply),/Unexpected migration history/)}finally{await db.stop()}})
test('Sprint 15 guard aborts wrong history and transaction rolls back late failure',async()=>{const db=await initialize();try{const apply=await sql(`10-APPLY-${version}.sql`);await db.query("insert into supabase_migrations.schema_migrations(version,name)values('20990101000000','unexpected')");await assert.rejects(db.query(apply),/Unexpected migration history/);assert.equal(await db.query("select count(*) from information_schema.columns where table_schema='public' and table_name='registrations' and column_name='payment_reported_at'"),'0');await db.query("delete from supabase_migrations.schema_migrations where version='20990101000000'");await db.query('grant update(payment_status) on public.registrations to anon');await assert.rejects(db.query(apply),/Private column grants/);await db.query('revoke update(payment_status) on public.registrations from anon');await assert.rejects(db.query(apply.replace('-- END EXACT REVIEWED SOURCE',"update public.registrations set total_amount=1; -- END EXACT REVIEWED SOURCE")),/Existing application rows changed/);await assert.rejects(db.query(apply.replace('COMMIT;','select 1/0; COMMIT;')),/division by zero/);assert.equal(await db.query(`select count(*) from supabase_migrations.schema_migrations where version='${version}'`),'0');assert.equal(await db.query("select count(*) from information_schema.columns where table_schema='public' and table_name='registrations' and column_name='payment_reported_at'"),'0')}finally{await db.stop()}})


test('snapshot disappears after rollback in the same connection',async()=>{const db=await initialize();try{const apply=await sql(`10-APPLY-${version}.sql`);await db.query(apply.replace('DROP TABLE pg_temp.sprint15_review_snapshot;','').replace('COMMIT;',`ROLLBACK; DO $qa$ BEGIN IF EXISTS(select 1 from pg_class where relname='sprint15_review_snapshot') THEN RAISE EXCEPTION 'Snapshot survives rollback'; END IF; END; $qa$;`));assert.equal(await db.query(`select count(*) from supabase_migrations.schema_migrations where version='${version}'`),'0')}finally{await db.stop()}})
