-- READ ONLY. Zero expected unless stated. Baseline exceptions must be reviewed, never silently repaired.
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY;
select count(*) as duplicate_accounting_rows from (select registration_id,provider from public.payments group by registration_id,provider having count(*)>1) d;
select count(*) as mixed_provider_groups from (select registration_id from public.payments group by registration_id having count(distinct provider)>1) d;
select count(*) as invalid_payment_correlations from public.payments p left join public.registrations r on r.id=p.registration_id where r.id is null or r.payment_method is distinct from p.provider or p.amount is distinct from r.total_amount or p.currency is distinct from 'ARS' or p.status is distinct from r.payment_status or (p.status='approved' and ((p.paid_at is null and not(p.provider='mercadopago' and p.amount=0)) or r.attendance_status is distinct from 'confirmed')) or (p.status<>'approved' and p.paid_at is not null) or (p.provider in ('transfer','mercadopago') and p.status<>'approved' and r.attendance_status is distinct from 'pending') or (p.provider='mercadopago' and (p.external_reference is distinct from r.id::text or (p.amount>0 and (p.provider_preference_id is null or length(p.provider_preference_id)=0)) or (p.status='approved' and p.amount>0 and p.provider_payment_id is null))) or (p.provider='transfer' and (p.provider_payment_id is not null or p.provider_preference_id is not null or p.external_reference is not null));
select count(*) as invalid_guest_groups from public.registrations r join lateral (select count(*) as n,count(*) filter(where age_category='adult') as a,count(*) filter(where age_category='child') as c,count(*) filter(where age_category='young_child') as y,count(*) filter(where age_category is null or age_category not in ('adult','child','young_child') or first_name is null or last_name is null or length(btrim(first_name)) not between 1 and 80 or length(btrim(last_name)) not between 1 and 80 or first_name<>btrim(first_name) or last_name<>btrim(last_name)) as bad from public.guests where registration_id=r.id) g on true where g.n>0 and (g.n<>r.guest_count or g.a<>r.adult_count or g.c<>r.child_count or g.y<>r.young_child_count or g.bad>0);
-- An unfinished RSVP may legitimately have zero guests; reported/approved transfer may not.
select count(*) as invalid_registration_fields from public.registrations r where wedding_id is null or not exists(select 1 from public.weddings w where w.id=r.wedding_id) or guest_count not between 1 and 20 or adult_count<0 or child_count<0 or young_child_count<0 or guest_count<>adult_count+child_count+young_child_count or total_amount<0 or total_amount::text in ('NaN','Infinity','-Infinity') or attendance_status is null or attendance_status not in ('pending','confirmed','cancelled') or payment_status is null or payment_status not in ('pending','approved','rejected','cancelled') or (payment_method is not null and payment_method not in ('cash','mercadopago','transfer')) or (management_token_hash is not null and management_token_hash !~ '^[a-f0-9]{64}$');
select count(*) as orphan_guests from public.guests g where not exists(select 1 from public.registrations r where r.id=g.registration_id);
select count(*) as invalid_attempt_correlations from public.mercadopago_payment_attempts a left join public.payments p on p.id=a.payment_id where p.id is null or p.provider is distinct from 'mercadopago' or a.amount is distinct from p.amount or a.currency is distinct from 'ARS' or ((a.status='approved') is distinct from (a.paid_at is not null));
select count(*) as unexpected_transfer_registrations_before_rollout from public.registrations where payment_method='transfer';
select count(*) as unexpected_transfer_payments_before_rollout from public.payments where provider='transfer';
select count(*) as unexpected_reported_before_rollout from public.registrations r where to_jsonb(r)->>'payment_reported_at' is not null;
select count(*) as expected_active_weddings from public.weddings where slug='ricardo-sabrina-2026' and is_active; -- expected 1
select 'registrations' as object,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(r)-'payment_reported_at' order by id)::text,'[]')) as fingerprint from public.registrations r
union all select 'guests',count(*),md5(coalesce(jsonb_agg(to_jsonb(g) order by id)::text,'[]')) from public.guests g
union all select 'payments',count(*),md5(coalesce(jsonb_agg(to_jsonb(p) order by id)::text,'[]')) from public.payments p
union all select 'mercadopago_payment_attempts',count(*),md5(coalesce(jsonb_agg(to_jsonb(a) order by provider_payment_id)::text,'[]')) from public.mercadopago_payment_attempts a
union all select 'admin_users',count(*),md5(coalesce(jsonb_agg(to_jsonb(a) order by user_id)::text,'[]')) from public.admin_users a
union all select 'weddings',count(*),md5(coalesce(jsonb_agg(to_jsonb(w) order by id)::text,'[]')) from public.weddings w;
select 'legacy_QA_NULL_token' as object,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(r)-'payment_reported_at' order by id)::text,'[]')) as fingerprint from public.registrations r where management_token_hash is null;
select 'MP_registrations' as object,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(r)-'payment_reported_at' order by id)::text,'[]')) as fingerprint from public.registrations r where payment_method='mercadopago';
select 'cash_registrations' as object,count(*) as rows,md5(coalesce(jsonb_agg(to_jsonb(r)-'payment_reported_at' order by id)::text,'[]')) as fingerprint from public.registrations r where payment_method='cash';
COMMIT;
